spring.application.name=JobPortalApplication
server.port=8080

# =========================
# DATABASE (MySQL)
# =========================
#spring.datasource.url=jdbc:mysql://localhost:3306/job_portal_v1?useSSL=false&serverTimezone=UTC
spring.datasource.url=jdbc:mysql://localhost:3306/job_portal_v1?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=test

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =========================
# JPA / HIBERNATE
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# =========================
# JWT CONFIG
# =========================
spring.jwt.secret=c4dff1ea-0daa-4e6c-b6a1-003d489033ce
spring.jwt.expiration=36000000
